"""Build docs/traceability.md: requirements (docs/spec.md) <-> tests (pytest req markers) <-> outcomes.

Runs the test suite once, in-process, recording each test's ``req`` marker and outcome, then
checks traceability in both directions:

* every requirement verified by test has at least one test, and all of them passed;
* every test traces to a requirement, or is listed as untraced (characterisation, CLI);
* requirements verified by demonstration point at the evidence (results.md, CI).

    python ci/trace_matrix.py            # exit 1 if a T requirement has no passing test
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SPEC, OUT = ROOT / "docs" / "spec.md", ROOT / "docs" / "traceability.md"


def requirements() -> list[dict]:
    rows = []
    for line in SPEC.read_text().splitlines():
        m = re.match(r"^\| (SF-\d+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \| ([^|]+) \|$", line)
        if m:
            rows.append(dict(id=m[1], type=m[2].strip(), pattern=m[3].strip(), text=m[4].strip(), method=m[5].strip()))
    return rows


class Collector:
    def __init__(self):
        self.reqs: dict[str, list[str]] = {}
        self.outcome: dict[str, str] = {}

    def pytest_collection_modifyitems(self, items):
        for it in items:
            self.reqs[it.nodeid] = [a for m in it.iter_markers("req") for a in m.args]

    def pytest_runtest_logreport(self, report):
        if report.when == "call" or (report.when == "setup" and report.outcome != "passed"):
            self.outcome[report.nodeid] = report.outcome


def demonstration_evidence(req: dict) -> str:
    if "results.md" in req["method"]:
        text = (ROOT / "examples" / "results.md").read_text()
        m = re.search(r"peak resident memory ([\d,]+) MB", text)
        return f"`examples/results.md`: peak resident memory {m[1]} MB" if m else "results.md: not found"
    if "GitHub Actions" in req["method"]:
        return "GitHub Actions runs the whole suite on `ubuntu-24.04` runners with CPU-only PyTorch"
    return ""


def main() -> int:
    col = Collector()
    code = pytest.main(["-q", "-p", "no:logging", "-p", "no:cacheprovider", str(ROOT / "tests")], plugins=[col])
    by_req: dict[str, list[str]] = defaultdict(list)
    for node, ids in col.reqs.items():
        for i in ids:
            by_req[i].append(node)
    reqs = requirements()
    known = {r["id"] for r in reqs}
    lines = ["# simfront: traceability matrix", "",
             "Generated by `ci/trace_matrix.py` from [`spec.md`](spec.md) and the test run itself; do not edit.", "",
             "| Requirement | Pattern | Method | Verified by | Result |", "|---|---|---|---|---|"]
    gaps = 0
    for r in reqs:
        tests = by_req.get(r["id"], [])
        if r["method"].startswith("T"):
            res = [col.outcome.get(t, "not run") for t in tests]
            ok = bool(tests) and all(x == "passed" for x in res)
            gaps += not ok
            names = "<br>".join(f"`{t.split('/')[-1]}`" for t in tests) or "**no test**"
            verdict = f"{sum(x == 'passed' for x in res)}/{len(tests)} passed" if tests else "**GAP**"
        else:
            names, verdict = demonstration_evidence(r), "demonstrated"
        lines.append(f"| **{r['id']}** {r['text']} | {r['pattern']} | {r['method']} | {names} | {verdict} |")
    untraced = [n for n, ids in col.reqs.items() if not ids]
    unknown = sorted({i for ids in col.reqs.values() for i in ids} - known)
    n_traced = sum(1 for ids in col.reqs.values() if ids)
    lines += ["", f"**Summary.** {len(reqs)} requirements; {len(col.reqs)} tests, {n_traced} traced to a requirement; "
              f"{gaps} requirement(s) without a passing test; test run exit code {int(code)}.", ""]
    lines += ["Tests that trace to no requirement (characterisation and CLI tests: they pin behaviour that is not "
              "itself required):", ""] + [f"* `{n.split('/')[-1]}`" for n in untraced]
    if unknown:
        lines += ["", f"Markers naming requirements that are not in the spec: {unknown}"]
        gaps += 1
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 1 if gaps or code else 0


if __name__ == "__main__":
    sys.exit(main())
